// This file will be auto-generated by:
//   supabase gen types typescript --db-url <connection_string> > src/lib/supabase.ts
// Placeholder types until generation is run against the live database.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			patients: {
				Row: {
					id: number;
					created_at: string;
					last_name: string;
					first_name: string;
					date_of_birth: string;
					note: string;
					updated_at: string | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					last_name: string;
					first_name: string;
					date_of_birth: string;
					note?: string;
					updated_at?: string | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					last_name?: string;
					first_name?: string;
					date_of_birth?: string;
					note?: string;
					updated_at?: string | null;
				};
				Relationships: [];
			};
			denials: {
				Row: {
					id: number;
					created_at: string;
					patient_id: number;
					service_start_date: string;
					service_end_date: string | null;
					billed_amount: number | null;
					paid_amount: number | null;
					is_closed: boolean;
					follow_up_date: string | null;
					updated_at: string | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					patient_id: number;
					service_start_date: string;
					service_end_date?: string | null;
					billed_amount?: number | null;
					paid_amount?: number | null;
					is_closed?: boolean;
					follow_up_date?: string | null;
					updated_at?: string | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					patient_id?: number;
					service_start_date?: string;
					service_end_date?: string | null;
					billed_amount?: number | null;
					paid_amount?: number | null;
					is_closed?: boolean;
					follow_up_date?: string | null;
					updated_at?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: 'denials_patient_id_fkey';
						columns: ['patient_id'];
						isOneToOne: false;
						referencedRelation: 'patients';
						referencedColumns: ['id'];
					}
				];
			};
			notes: {
				Row: {
					id: number;
					created_at: string;
					modified_at: string | null;
					note: string;
					created_by: string | null;
					denial_id: number;
					modified_by: string | null;
					updated_at: string | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					modified_at?: string | null;
					note: string;
					created_by?: string | null;
					denial_id: number;
					modified_by?: string | null;
					updated_at?: string | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					modified_at?: string | null;
					note?: string;
					created_by?: string | null;
					denial_id?: number;
					modified_by?: string | null;
					updated_at?: string | null;
				};
				Relationships: [
					{
						foreignKeyName: 'notes_denial_id_fkey';
						columns: ['denial_id'];
						isOneToOne: false;
						referencedRelation: 'denials';
						referencedColumns: ['id'];
					}
				];
			};
			files: {
				Row: {
					name: string;
					created_at: string;
					size: number | null;
					mimetype: string | null;
					metadata: Json | null;
				};
				Insert: {
					name: string;
					created_at?: string;
					size?: number | null;
					mimetype?: string | null;
					metadata?: Json | null;
				};
				Update: {
					name?: string;
					created_at?: string;
					size?: number | null;
					mimetype?: string | null;
					metadata?: Json | null;
				};
				Relationships: [];
			};
			notes_files: {
				Row: {
					note_id: number;
					file_name: string;
					created_at: string;
				};
				Insert: {
					note_id: number;
					file_name: string;
					created_at?: string;
				};
				Update: {
					note_id?: number;
					file_name?: string;
					created_at?: string;
				};
				Relationships: [];
			};
			patients_files: {
				Row: {
					patient_id: number;
					file_name: string;
					created_at: string;
				};
				Insert: {
					patient_id: number;
					file_name: string;
					created_at?: string;
				};
				Update: {
					patient_id?: number;
					file_name?: string;
					created_at?: string;
				};
				Relationships: [];
			};
			insurances: {
				Row: {
					id: number;
					created_at: string;
					name: string;
					note: string | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					name: string;
					note?: string | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					name?: string;
					note?: string | null;
				};
				Relationships: [];
			};
			denials_insurances: {
				Row: {
					denial_id: number;
					insurance_id: number;
					created_at: string;
				};
				Insert: {
					denial_id: number;
					insurance_id: number;
					created_at?: string;
				};
				Update: {
					denial_id?: number;
					insurance_id?: number;
					created_at?: string;
				};
				Relationships: [
					{
						foreignKeyName: 'denials_insurances_denial_id_fkey';
						columns: ['denial_id'];
						isOneToOne: false;
						referencedRelation: 'denials';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'denials_insurances_insurance_id_fkey';
						columns: ['insurance_id'];
						isOneToOne: false;
						referencedRelation: 'insurances';
						referencedColumns: ['id'];
					}
				];
			};
			labels: {
				Row: {
					id: number;
					created_at: string;
					order: number | null;
					label_name: string;
					bg_color: string;
					txt_color: string;
				};
				Insert: {
					id?: number;
					created_at?: string;
					order?: number | null;
					label_name: string;
					bg_color: string;
					txt_color: string;
				};
				Update: {
					id?: number;
					created_at?: string;
					order?: number | null;
					label_name?: string;
					bg_color?: string;
					txt_color?: string;
				};
				Relationships: [];
			};
			denials_labels: {
				Row: {
					denial_id: number;
					label_id: number;
					created_at: string;
				};
				Insert: {
					denial_id: number;
					label_id: number;
					created_at?: string;
				};
				Update: {
					denial_id?: number;
					label_id?: number;
					created_at?: string;
				};
				Relationships: [
					{
						foreignKeyName: 'denials_labels_denial_id_fkey';
						columns: ['denial_id'];
						isOneToOne: false;
						referencedRelation: 'denials';
						referencedColumns: ['id'];
					},
					{
						foreignKeyName: 'denials_labels_label_id_fkey';
						columns: ['label_id'];
						isOneToOne: false;
						referencedRelation: 'labels';
						referencedColumns: ['id'];
					}
				];
			};
			users: {
				Row: {
					id: string;
					created_at: string;
					username: string | null;
					role: number | null;
				};
				Insert: {
					id?: string;
					created_at?: string;
					username?: string | null;
					role?: number | null;
				};
				Update: {
					id?: string;
					created_at?: string;
					username?: string | null;
					role?: number | null;
				};
				Relationships: [
					{
						foreignKeyName: 'users_role_fkey';
						columns: ['role'];
						isOneToOne: false;
						referencedRelation: 'roles';
						referencedColumns: ['id'];
					}
				];
			};
			roles: {
				Row: {
					id: number;
					created_at: string;
					role_name: string;
					permissions: Json | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					role_name: string;
					permissions?: Json | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					role_name?: string;
					permissions?: Json | null;
				};
				Relationships: [];
			};
			preferences: {
				Row: {
					id: number;
					created_at: string;
					name: string;
					data_type: string;
					value: string | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					name: string;
					data_type: string;
					value?: string | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					name?: string;
					data_type?: string;
					value?: string | null;
				};
				Relationships: [];
			};
			preference_users: {
				Row: {
					preference_id: number;
					user_id: string;
					created_at: string;
					user_value: string | null;
				};
				Insert: {
					preference_id: number;
					user_id: string;
					created_at?: string;
					user_value?: string | null;
				};
				Update: {
					preference_id?: number;
					user_id?: string;
					created_at?: string;
					user_value?: string | null;
				};
				Relationships: [];
			};
			audit_log: {
				Row: {
					id: number;
					created_at: string;
					user_id: string | null;
					action: string;
					resource_type: string;
					resource_id: string | null;
					ip_address: string | null;
					user_agent: string | null;
					details: Json | null;
				};
				Insert: {
					id?: number;
					created_at?: string;
					user_id?: string | null;
					action: string;
					resource_type: string;
					resource_id?: string | null;
					ip_address?: string | null;
					user_agent?: string | null;
					details?: Json | null;
				};
				Update: {
					id?: number;
					created_at?: string;
					user_id?: string | null;
					action?: string;
					resource_type?: string;
					resource_id?: string | null;
					ip_address?: string | null;
					user_agent?: string | null;
					details?: Json | null;
				};
				Relationships: [];
			};
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
}
