services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - supabase

networks:
  supabase:
    name: supabase_default
    external: true
