services:
  server:
    build:
      context: .
      args:
        PUBLIC_SUPABASE_URL: ${SUPABASE_PUBLIC_URL}
        PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
        PRIVATE_SUPABASE_SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
    pull_policy: build
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000 || exit 1']
      interval: 1m30s
      timeout: 10s
      retries: 3
