create table "public"."denials_insurances" (
    "created_at" timestamp with time zone not null default now(),
    "denial_id" bigint not null,
    "insurance_id" bigint not null
);


alter table "public"."denials_insurances" enable row level security;

create table "public"."insurances" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "note" character varying
);


alter table "public"."insurances" enable row level security;

CREATE UNIQUE INDEX denials_insurances_pkey ON public.denials_insurances USING btree (denial_id, insurance_id);

CREATE UNIQUE INDEX insurances_pkey ON public.insurances USING btree (id);

alter table "public"."denials_insurances" add constraint "denials_insurances_pkey" PRIMARY KEY using index "denials_insurances_pkey";

alter table "public"."insurances" add constraint "insurances_pkey" PRIMARY KEY using index "insurances_pkey";

alter table "public"."denials_insurances" add constraint "denials_insurances_denial_id_fkey" FOREIGN KEY (denial_id) REFERENCES denials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials_insurances" validate constraint "denials_insurances_denial_id_fkey";

alter table "public"."denials_insurances" add constraint "denials_insurances_insurance_id_fkey" FOREIGN KEY (insurance_id) REFERENCES insurances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials_insurances" validate constraint "denials_insurances_insurance_id_fkey";

grant delete on table "public"."denials_insurances" to "anon";

grant insert on table "public"."denials_insurances" to "anon";

grant references on table "public"."denials_insurances" to "anon";

grant select on table "public"."denials_insurances" to "anon";

grant trigger on table "public"."denials_insurances" to "anon";

grant truncate on table "public"."denials_insurances" to "anon";

grant update on table "public"."denials_insurances" to "anon";

grant delete on table "public"."denials_insurances" to "authenticated";

grant insert on table "public"."denials_insurances" to "authenticated";

grant references on table "public"."denials_insurances" to "authenticated";

grant select on table "public"."denials_insurances" to "authenticated";

grant trigger on table "public"."denials_insurances" to "authenticated";

grant truncate on table "public"."denials_insurances" to "authenticated";

grant update on table "public"."denials_insurances" to "authenticated";

grant delete on table "public"."denials_insurances" to "service_role";

grant insert on table "public"."denials_insurances" to "service_role";

grant references on table "public"."denials_insurances" to "service_role";

grant select on table "public"."denials_insurances" to "service_role";

grant trigger on table "public"."denials_insurances" to "service_role";

grant truncate on table "public"."denials_insurances" to "service_role";

grant update on table "public"."denials_insurances" to "service_role";

grant delete on table "public"."insurances" to "anon";

grant insert on table "public"."insurances" to "anon";

grant references on table "public"."insurances" to "anon";

grant select on table "public"."insurances" to "anon";

grant trigger on table "public"."insurances" to "anon";

grant truncate on table "public"."insurances" to "anon";

grant update on table "public"."insurances" to "anon";

grant delete on table "public"."insurances" to "authenticated";

grant insert on table "public"."insurances" to "authenticated";

grant references on table "public"."insurances" to "authenticated";

grant select on table "public"."insurances" to "authenticated";

grant trigger on table "public"."insurances" to "authenticated";

grant truncate on table "public"."insurances" to "authenticated";

grant update on table "public"."insurances" to "authenticated";

grant delete on table "public"."insurances" to "service_role";

grant insert on table "public"."insurances" to "service_role";

grant references on table "public"."insurances" to "service_role";

grant select on table "public"."insurances" to "service_role";

grant trigger on table "public"."insurances" to "service_role";

grant truncate on table "public"."insurances" to "service_role";

grant update on table "public"."insurances" to "service_role";

create policy "Enable all access for authenticated users"
on "public"."denials_insurances"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."insurances"
as permissive
for all
to authenticated
using (true);



