create table "public"."denial_labels" (
    "created_at" timestamp with time zone not null default now(),
    "denial_id" bigint not null,
    "label_id" bigint not null
);


create table "public"."denial_notes" (
    "created_at" timestamp with time zone not null default now(),
    "denial_id" bigint not null,
    "note_id" bigint not null
);


create table "public"."denials" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "patient_id" bigint not null,
    "service_start_date" date not null,
    "service_end_date" date,
    "billed_amount" numeric,
    "paid_amount" numeric
);


create table "public"."labels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label_name" character varying not null,
    "color_hex" character varying not null
);


create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "modified_at" timestamp with time zone,
    "user_id" uuid not null,
    "note" character varying not null
);


create table "public"."patients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "last_name" character varying not null,
    "first_name" character varying not null,
    "date_of_birth" date not null,
    "note" character varying
);


create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role_name" character varying not null
);


create table "public"."user_roles" (
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "role_id" bigint not null
);


create table "public"."users" (
    "id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "username" character varying
);


CREATE UNIQUE INDEX denial_labels_pkey ON public.denial_labels USING btree (denial_id, label_id);

CREATE UNIQUE INDEX denial_notes_pkey ON public.denial_notes USING btree (denial_id, note_id);

CREATE UNIQUE INDEX denials_pkey ON public.denials USING btree (id);

CREATE UNIQUE INDEX labels_pkey ON public.labels USING btree (id);

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (user_id, role_id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."denial_labels" add constraint "denial_labels_pkey" PRIMARY KEY using index "denial_labels_pkey";

alter table "public"."denial_notes" add constraint "denial_notes_pkey" PRIMARY KEY using index "denial_notes_pkey";

alter table "public"."denials" add constraint "denials_pkey" PRIMARY KEY using index "denials_pkey";

alter table "public"."labels" add constraint "labels_pkey" PRIMARY KEY using index "labels_pkey";

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."patients" add constraint "patients_pkey" PRIMARY KEY using index "patients_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."denial_labels" add constraint "public_denial_labels_denial_id_fkey" FOREIGN KEY (denial_id) REFERENCES denials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denial_labels" validate constraint "public_denial_labels_denial_id_fkey";

alter table "public"."denial_labels" add constraint "public_denial_labels_label_id_fkey" FOREIGN KEY (label_id) REFERENCES labels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denial_labels" validate constraint "public_denial_labels_label_id_fkey";

alter table "public"."denial_notes" add constraint "public_denial_notes_denial_id_fkey" FOREIGN KEY (denial_id) REFERENCES denials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denial_notes" validate constraint "public_denial_notes_denial_id_fkey";

alter table "public"."denial_notes" add constraint "public_denial_notes_note_id_fkey" FOREIGN KEY (note_id) REFERENCES notes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denial_notes" validate constraint "public_denial_notes_note_id_fkey";

alter table "public"."denials" add constraint "public_denials_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patients(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials" validate constraint "public_denials_patient_id_fkey";

alter table "public"."notes" add constraint "public_notes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes" validate constraint "public_notes_user_id_fkey";

alter table "public"."user_roles" add constraint "public_user_roles_role_id_fkey" FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "public_user_roles_role_id_fkey";

alter table "public"."user_roles" add constraint "public_user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "public_user_roles_user_id_fkey";

alter table "public"."users" add constraint "public_users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "public_users_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.users (id, username)
  values (new.id, new.raw_user_meta_data ->> 'username');
  return new;
end;
$function$
;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

grant delete on table "public"."denial_labels" to "anon";

grant insert on table "public"."denial_labels" to "anon";

grant references on table "public"."denial_labels" to "anon";

grant select on table "public"."denial_labels" to "anon";

grant trigger on table "public"."denial_labels" to "anon";

grant truncate on table "public"."denial_labels" to "anon";

grant update on table "public"."denial_labels" to "anon";

grant delete on table "public"."denial_labels" to "authenticated";

grant insert on table "public"."denial_labels" to "authenticated";

grant references on table "public"."denial_labels" to "authenticated";

grant select on table "public"."denial_labels" to "authenticated";

grant trigger on table "public"."denial_labels" to "authenticated";

grant truncate on table "public"."denial_labels" to "authenticated";

grant update on table "public"."denial_labels" to "authenticated";

grant delete on table "public"."denial_labels" to "service_role";

grant insert on table "public"."denial_labels" to "service_role";

grant references on table "public"."denial_labels" to "service_role";

grant select on table "public"."denial_labels" to "service_role";

grant trigger on table "public"."denial_labels" to "service_role";

grant truncate on table "public"."denial_labels" to "service_role";

grant update on table "public"."denial_labels" to "service_role";

grant delete on table "public"."denial_notes" to "anon";

grant insert on table "public"."denial_notes" to "anon";

grant references on table "public"."denial_notes" to "anon";

grant select on table "public"."denial_notes" to "anon";

grant trigger on table "public"."denial_notes" to "anon";

grant truncate on table "public"."denial_notes" to "anon";

grant update on table "public"."denial_notes" to "anon";

grant delete on table "public"."denial_notes" to "authenticated";

grant insert on table "public"."denial_notes" to "authenticated";

grant references on table "public"."denial_notes" to "authenticated";

grant select on table "public"."denial_notes" to "authenticated";

grant trigger on table "public"."denial_notes" to "authenticated";

grant truncate on table "public"."denial_notes" to "authenticated";

grant update on table "public"."denial_notes" to "authenticated";

grant delete on table "public"."denial_notes" to "service_role";

grant insert on table "public"."denial_notes" to "service_role";

grant references on table "public"."denial_notes" to "service_role";

grant select on table "public"."denial_notes" to "service_role";

grant trigger on table "public"."denial_notes" to "service_role";

grant truncate on table "public"."denial_notes" to "service_role";

grant update on table "public"."denial_notes" to "service_role";

grant delete on table "public"."denials" to "anon";

grant insert on table "public"."denials" to "anon";

grant references on table "public"."denials" to "anon";

grant select on table "public"."denials" to "anon";

grant trigger on table "public"."denials" to "anon";

grant truncate on table "public"."denials" to "anon";

grant update on table "public"."denials" to "anon";

grant delete on table "public"."denials" to "authenticated";

grant insert on table "public"."denials" to "authenticated";

grant references on table "public"."denials" to "authenticated";

grant select on table "public"."denials" to "authenticated";

grant trigger on table "public"."denials" to "authenticated";

grant truncate on table "public"."denials" to "authenticated";

grant update on table "public"."denials" to "authenticated";

grant delete on table "public"."denials" to "service_role";

grant insert on table "public"."denials" to "service_role";

grant references on table "public"."denials" to "service_role";

grant select on table "public"."denials" to "service_role";

grant trigger on table "public"."denials" to "service_role";

grant truncate on table "public"."denials" to "service_role";

grant update on table "public"."denials" to "service_role";

grant delete on table "public"."labels" to "anon";

grant insert on table "public"."labels" to "anon";

grant references on table "public"."labels" to "anon";

grant select on table "public"."labels" to "anon";

grant trigger on table "public"."labels" to "anon";

grant truncate on table "public"."labels" to "anon";

grant update on table "public"."labels" to "anon";

grant delete on table "public"."labels" to "authenticated";

grant insert on table "public"."labels" to "authenticated";

grant references on table "public"."labels" to "authenticated";

grant select on table "public"."labels" to "authenticated";

grant trigger on table "public"."labels" to "authenticated";

grant truncate on table "public"."labels" to "authenticated";

grant update on table "public"."labels" to "authenticated";

grant delete on table "public"."labels" to "service_role";

grant insert on table "public"."labels" to "service_role";

grant references on table "public"."labels" to "service_role";

grant select on table "public"."labels" to "service_role";

grant trigger on table "public"."labels" to "service_role";

grant truncate on table "public"."labels" to "service_role";

grant update on table "public"."labels" to "service_role";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

grant delete on table "public"."patients" to "anon";

grant insert on table "public"."patients" to "anon";

grant references on table "public"."patients" to "anon";

grant select on table "public"."patients" to "anon";

grant trigger on table "public"."patients" to "anon";

grant truncate on table "public"."patients" to "anon";

grant update on table "public"."patients" to "anon";

grant delete on table "public"."patients" to "authenticated";

grant insert on table "public"."patients" to "authenticated";

grant references on table "public"."patients" to "authenticated";

grant select on table "public"."patients" to "authenticated";

grant trigger on table "public"."patients" to "authenticated";

grant truncate on table "public"."patients" to "authenticated";

grant update on table "public"."patients" to "authenticated";

grant delete on table "public"."patients" to "service_role";

grant insert on table "public"."patients" to "service_role";

grant references on table "public"."patients" to "service_role";

grant select on table "public"."patients" to "service_role";

grant trigger on table "public"."patients" to "service_role";

grant truncate on table "public"."patients" to "service_role";

grant update on table "public"."patients" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


