create table "public"."denials" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "patient_id" bigint not null,
    "service_start_date" date not null,
    "service_end_date" date,
    "billed_amount" numeric,
    "paid_amount" numeric
);


alter table "public"."denials" enable row level security;

create table "public"."denials_labels" (
    "created_at" timestamp with time zone not null default now(),
    "denial_id" bigint not null,
    "label_id" bigint not null
);


alter table "public"."denials_labels" enable row level security;

create table "public"."files" (
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "size" bigint,
    "mimetype" text,
    "metadata" jsonb
);


alter table "public"."files" enable row level security;

create table "public"."labels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "order" numeric,
    "label_name" character varying not null,
    "bg_color" character varying not null,
    "txt_color" character varying not null
);


alter table "public"."labels" enable row level security;

create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "modified_at" timestamp with time zone,
    "note" character varying not null,
    "created_by" uuid,
    "denial_id" bigint not null,
    "modified_by" uuid
);


alter table "public"."notes" enable row level security;

create table "public"."notes_files" (
    "created_at" timestamp with time zone not null default now(),
    "note_id" bigint not null,
    "file_name" text not null
);


alter table "public"."notes_files" enable row level security;

create table "public"."patients" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "last_name" character varying not null,
    "first_name" character varying not null,
    "date_of_birth" date not null,
    "note" character varying default ''::character varying
);


alter table "public"."patients" enable row level security;

create table "public"."roles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "role_name" character varying not null,
    "permissions" jsonb
);


alter table "public"."roles" enable row level security;

create table "public"."users" (
    "id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now(),
    "username" character varying,
    "role" bigint
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX denials_labels_pkey ON public.denials_labels USING btree (denial_id, label_id);

CREATE UNIQUE INDEX denials_pkey ON public.denials USING btree (id);

CREATE UNIQUE INDEX files_pkey ON public.files USING btree (name);

CREATE UNIQUE INDEX labels_pkey ON public.labels USING btree (id);

CREATE UNIQUE INDEX notes_files_pkey ON public.notes_files USING btree (note_id, file_name);

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (id);

CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."denials" add constraint "denials_pkey" PRIMARY KEY using index "denials_pkey";

alter table "public"."denials_labels" add constraint "denials_labels_pkey" PRIMARY KEY using index "denials_labels_pkey";

alter table "public"."files" add constraint "files_pkey" PRIMARY KEY using index "files_pkey";

alter table "public"."labels" add constraint "labels_pkey" PRIMARY KEY using index "labels_pkey";

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";

alter table "public"."notes_files" add constraint "notes_files_pkey" PRIMARY KEY using index "notes_files_pkey";

alter table "public"."patients" add constraint "patients_pkey" PRIMARY KEY using index "patients_pkey";

alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."denials" add constraint "public_denials_patient_id_fkey" FOREIGN KEY (patient_id) REFERENCES patients(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials" validate constraint "public_denials_patient_id_fkey";

alter table "public"."denials_labels" add constraint "public_denials_labels_denial_id_fkey" FOREIGN KEY (denial_id) REFERENCES denials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials_labels" validate constraint "public_denials_labels_denial_id_fkey";

alter table "public"."denials_labels" add constraint "public_denials_labels_label_id_fkey" FOREIGN KEY (label_id) REFERENCES labels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."denials_labels" validate constraint "public_denials_labels_label_id_fkey";

alter table "public"."notes" add constraint "public_notes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."notes" validate constraint "public_notes_created_by_fkey";

alter table "public"."notes" add constraint "public_notes_denial_id_fkey" FOREIGN KEY (denial_id) REFERENCES denials(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes" validate constraint "public_notes_denial_id_fkey";

alter table "public"."notes" add constraint "public_notes_modified_by_fkey" FOREIGN KEY (modified_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."notes" validate constraint "public_notes_modified_by_fkey";

alter table "public"."notes_files" add constraint "notes_files_file_name_fkey" FOREIGN KEY (file_name) REFERENCES files(name) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes_files" validate constraint "notes_files_file_name_fkey";

alter table "public"."notes_files" add constraint "notes_files_note_id_fkey" FOREIGN KEY (note_id) REFERENCES notes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notes_files" validate constraint "notes_files_note_id_fkey";

alter table "public"."users" add constraint "public_users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "public_users_id_fkey";

alter table "public"."users" add constraint "public_users_role_fkey" FOREIGN KEY (role) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."users" validate constraint "public_users_role_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.users (id, username)
  values (
    new.id,
    replace(new.email, '@supabase', '')
  );
  return new;
end;
$function$
;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

grant delete on table "public"."denials" to "anon";

grant insert on table "public"."denials" to "anon";

grant references on table "public"."denials" to "anon";

grant select on table "public"."denials" to "anon";

grant trigger on table "public"."denials" to "anon";

grant truncate on table "public"."denials" to "anon";

grant update on table "public"."denials" to "anon";

grant delete on table "public"."denials" to "authenticated";

grant insert on table "public"."denials" to "authenticated";

grant references on table "public"."denials" to "authenticated";

grant select on table "public"."denials" to "authenticated";

grant trigger on table "public"."denials" to "authenticated";

grant truncate on table "public"."denials" to "authenticated";

grant update on table "public"."denials" to "authenticated";

grant delete on table "public"."denials" to "service_role";

grant insert on table "public"."denials" to "service_role";

grant references on table "public"."denials" to "service_role";

grant select on table "public"."denials" to "service_role";

grant trigger on table "public"."denials" to "service_role";

grant truncate on table "public"."denials" to "service_role";

grant update on table "public"."denials" to "service_role";

grant delete on table "public"."denials_labels" to "anon";

grant insert on table "public"."denials_labels" to "anon";

grant references on table "public"."denials_labels" to "anon";

grant select on table "public"."denials_labels" to "anon";

grant trigger on table "public"."denials_labels" to "anon";

grant truncate on table "public"."denials_labels" to "anon";

grant update on table "public"."denials_labels" to "anon";

grant delete on table "public"."denials_labels" to "authenticated";

grant insert on table "public"."denials_labels" to "authenticated";

grant references on table "public"."denials_labels" to "authenticated";

grant select on table "public"."denials_labels" to "authenticated";

grant trigger on table "public"."denials_labels" to "authenticated";

grant truncate on table "public"."denials_labels" to "authenticated";

grant update on table "public"."denials_labels" to "authenticated";

grant delete on table "public"."denials_labels" to "service_role";

grant insert on table "public"."denials_labels" to "service_role";

grant references on table "public"."denials_labels" to "service_role";

grant select on table "public"."denials_labels" to "service_role";

grant trigger on table "public"."denials_labels" to "service_role";

grant truncate on table "public"."denials_labels" to "service_role";

grant update on table "public"."denials_labels" to "service_role";

grant delete on table "public"."files" to "anon";

grant insert on table "public"."files" to "anon";

grant references on table "public"."files" to "anon";

grant select on table "public"."files" to "anon";

grant trigger on table "public"."files" to "anon";

grant truncate on table "public"."files" to "anon";

grant update on table "public"."files" to "anon";

grant delete on table "public"."files" to "authenticated";

grant insert on table "public"."files" to "authenticated";

grant references on table "public"."files" to "authenticated";

grant select on table "public"."files" to "authenticated";

grant trigger on table "public"."files" to "authenticated";

grant truncate on table "public"."files" to "authenticated";

grant update on table "public"."files" to "authenticated";

grant delete on table "public"."files" to "service_role";

grant insert on table "public"."files" to "service_role";

grant references on table "public"."files" to "service_role";

grant select on table "public"."files" to "service_role";

grant trigger on table "public"."files" to "service_role";

grant truncate on table "public"."files" to "service_role";

grant update on table "public"."files" to "service_role";

grant delete on table "public"."labels" to "anon";

grant insert on table "public"."labels" to "anon";

grant references on table "public"."labels" to "anon";

grant select on table "public"."labels" to "anon";

grant trigger on table "public"."labels" to "anon";

grant truncate on table "public"."labels" to "anon";

grant update on table "public"."labels" to "anon";

grant delete on table "public"."labels" to "authenticated";

grant insert on table "public"."labels" to "authenticated";

grant references on table "public"."labels" to "authenticated";

grant select on table "public"."labels" to "authenticated";

grant trigger on table "public"."labels" to "authenticated";

grant truncate on table "public"."labels" to "authenticated";

grant update on table "public"."labels" to "authenticated";

grant delete on table "public"."labels" to "service_role";

grant insert on table "public"."labels" to "service_role";

grant references on table "public"."labels" to "service_role";

grant select on table "public"."labels" to "service_role";

grant trigger on table "public"."labels" to "service_role";

grant truncate on table "public"."labels" to "service_role";

grant update on table "public"."labels" to "service_role";

grant delete on table "public"."notes" to "anon";

grant insert on table "public"."notes" to "anon";

grant references on table "public"."notes" to "anon";

grant select on table "public"."notes" to "anon";

grant trigger on table "public"."notes" to "anon";

grant truncate on table "public"."notes" to "anon";

grant update on table "public"."notes" to "anon";

grant delete on table "public"."notes" to "authenticated";

grant insert on table "public"."notes" to "authenticated";

grant references on table "public"."notes" to "authenticated";

grant select on table "public"."notes" to "authenticated";

grant trigger on table "public"."notes" to "authenticated";

grant truncate on table "public"."notes" to "authenticated";

grant update on table "public"."notes" to "authenticated";

grant delete on table "public"."notes" to "service_role";

grant insert on table "public"."notes" to "service_role";

grant references on table "public"."notes" to "service_role";

grant select on table "public"."notes" to "service_role";

grant trigger on table "public"."notes" to "service_role";

grant truncate on table "public"."notes" to "service_role";

grant update on table "public"."notes" to "service_role";

grant delete on table "public"."notes_files" to "anon";

grant insert on table "public"."notes_files" to "anon";

grant references on table "public"."notes_files" to "anon";

grant select on table "public"."notes_files" to "anon";

grant trigger on table "public"."notes_files" to "anon";

grant truncate on table "public"."notes_files" to "anon";

grant update on table "public"."notes_files" to "anon";

grant delete on table "public"."notes_files" to "authenticated";

grant insert on table "public"."notes_files" to "authenticated";

grant references on table "public"."notes_files" to "authenticated";

grant select on table "public"."notes_files" to "authenticated";

grant trigger on table "public"."notes_files" to "authenticated";

grant truncate on table "public"."notes_files" to "authenticated";

grant update on table "public"."notes_files" to "authenticated";

grant delete on table "public"."notes_files" to "service_role";

grant insert on table "public"."notes_files" to "service_role";

grant references on table "public"."notes_files" to "service_role";

grant select on table "public"."notes_files" to "service_role";

grant trigger on table "public"."notes_files" to "service_role";

grant truncate on table "public"."notes_files" to "service_role";

grant update on table "public"."notes_files" to "service_role";

grant delete on table "public"."patients" to "anon";

grant insert on table "public"."patients" to "anon";

grant references on table "public"."patients" to "anon";

grant select on table "public"."patients" to "anon";

grant trigger on table "public"."patients" to "anon";

grant truncate on table "public"."patients" to "anon";

grant update on table "public"."patients" to "anon";

grant delete on table "public"."patients" to "authenticated";

grant insert on table "public"."patients" to "authenticated";

grant references on table "public"."patients" to "authenticated";

grant select on table "public"."patients" to "authenticated";

grant trigger on table "public"."patients" to "authenticated";

grant truncate on table "public"."patients" to "authenticated";

grant update on table "public"."patients" to "authenticated";

grant delete on table "public"."patients" to "service_role";

grant insert on table "public"."patients" to "service_role";

grant references on table "public"."patients" to "service_role";

grant select on table "public"."patients" to "service_role";

grant trigger on table "public"."patients" to "service_role";

grant truncate on table "public"."patients" to "service_role";

grant update on table "public"."patients" to "service_role";

grant delete on table "public"."roles" to "anon";

grant insert on table "public"."roles" to "anon";

grant references on table "public"."roles" to "anon";

grant select on table "public"."roles" to "anon";

grant trigger on table "public"."roles" to "anon";

grant truncate on table "public"."roles" to "anon";

grant update on table "public"."roles" to "anon";

grant delete on table "public"."roles" to "authenticated";

grant insert on table "public"."roles" to "authenticated";

grant references on table "public"."roles" to "authenticated";

grant select on table "public"."roles" to "authenticated";

grant trigger on table "public"."roles" to "authenticated";

grant truncate on table "public"."roles" to "authenticated";

grant update on table "public"."roles" to "authenticated";

grant delete on table "public"."roles" to "service_role";

grant insert on table "public"."roles" to "service_role";

grant references on table "public"."roles" to "service_role";

grant select on table "public"."roles" to "service_role";

grant trigger on table "public"."roles" to "service_role";

grant truncate on table "public"."roles" to "service_role";

grant update on table "public"."roles" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Enable all access for authenticated users"
on "public"."denials"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."denials_labels"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."files"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."labels"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."notes"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."notes_files"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."patients"
as permissive
for all
to authenticated
using (true);


create policy "Enable all access for authenticated users"
on "public"."roles"
as permissive
for all
to authenticated
using (true);


create policy "Enable insert for initial setup"
on "public"."roles"
as permissive
for insert
to anon
with check ((NOT (EXISTS ( SELECT 1
   FROM users))));


create policy "Enable all access for authenticated users"
on "public"."users"
as permissive
for all
to authenticated
using (true);

create policy "Enable all access for authenticated users"
on "storage"."objects"
as permissive
for all 
to authenticated
using (true);

create policy "Enable all access for authenticated users"
on "storage"."buckets"
as permissive
for all 
to authenticated
using (true);
