create table "public"."preference_users" (
    "preference_id" bigint not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "user_value" text
);


alter table "public"."preference_users" enable row level security;

create table "public"."preferences" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "data_type" text not null,
    "value" text
);


alter table "public"."preferences" enable row level security;

CREATE UNIQUE INDEX preference_users_pkey ON public.preference_users USING btree (preference_id, user_id);

CREATE UNIQUE INDEX preferences_name_key ON public.preferences USING btree (name);

CREATE UNIQUE INDEX preferences_pkey ON public.preferences USING btree (id);

alter table "public"."preference_users" add constraint "preference_users_pkey" PRIMARY KEY using index "preference_users_pkey";

alter table "public"."preferences" add constraint "preferences_pkey" PRIMARY KEY using index "preferences_pkey";

alter table "public"."preference_users" add constraint "preference_users_preference_id_fkey" FOREIGN KEY (preference_id) REFERENCES preferences(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."preference_users" validate constraint "preference_users_preference_id_fkey";

alter table "public"."preference_users" add constraint "preference_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."preference_users" validate constraint "preference_users_user_id_fkey";

alter table "public"."preferences" add constraint "preferences_name_key" UNIQUE using index "preferences_name_key";

grant delete on table "public"."patients_files" to "postgres";

grant insert on table "public"."patients_files" to "postgres";

grant references on table "public"."patients_files" to "postgres";

grant select on table "public"."patients_files" to "postgres";

grant trigger on table "public"."patients_files" to "postgres";

grant truncate on table "public"."patients_files" to "postgres";

grant update on table "public"."patients_files" to "postgres";

grant delete on table "public"."preference_users" to "anon";

grant insert on table "public"."preference_users" to "anon";

grant references on table "public"."preference_users" to "anon";

grant select on table "public"."preference_users" to "anon";

grant trigger on table "public"."preference_users" to "anon";

grant truncate on table "public"."preference_users" to "anon";

grant update on table "public"."preference_users" to "anon";

grant delete on table "public"."preference_users" to "authenticated";

grant insert on table "public"."preference_users" to "authenticated";

grant references on table "public"."preference_users" to "authenticated";

grant select on table "public"."preference_users" to "authenticated";

grant trigger on table "public"."preference_users" to "authenticated";

grant truncate on table "public"."preference_users" to "authenticated";

grant update on table "public"."preference_users" to "authenticated";

grant delete on table "public"."preference_users" to "postgres";

grant insert on table "public"."preference_users" to "postgres";

grant references on table "public"."preference_users" to "postgres";

grant select on table "public"."preference_users" to "postgres";

grant trigger on table "public"."preference_users" to "postgres";

grant truncate on table "public"."preference_users" to "postgres";

grant update on table "public"."preference_users" to "postgres";

grant delete on table "public"."preference_users" to "service_role";

grant insert on table "public"."preference_users" to "service_role";

grant references on table "public"."preference_users" to "service_role";

grant select on table "public"."preference_users" to "service_role";

grant trigger on table "public"."preference_users" to "service_role";

grant truncate on table "public"."preference_users" to "service_role";

grant update on table "public"."preference_users" to "service_role";

grant delete on table "public"."preferences" to "anon";

grant insert on table "public"."preferences" to "anon";

grant references on table "public"."preferences" to "anon";

grant select on table "public"."preferences" to "anon";

grant trigger on table "public"."preferences" to "anon";

grant truncate on table "public"."preferences" to "anon";

grant update on table "public"."preferences" to "anon";

grant delete on table "public"."preferences" to "authenticated";

grant insert on table "public"."preferences" to "authenticated";

grant references on table "public"."preferences" to "authenticated";

grant select on table "public"."preferences" to "authenticated";

grant trigger on table "public"."preferences" to "authenticated";

grant truncate on table "public"."preferences" to "authenticated";

grant update on table "public"."preferences" to "authenticated";

grant delete on table "public"."preferences" to "postgres";

grant insert on table "public"."preferences" to "postgres";

grant references on table "public"."preferences" to "postgres";

grant select on table "public"."preferences" to "postgres";

grant trigger on table "public"."preferences" to "postgres";

grant truncate on table "public"."preferences" to "postgres";

grant update on table "public"."preferences" to "postgres";

grant delete on table "public"."preferences" to "service_role";

grant insert on table "public"."preferences" to "service_role";

grant references on table "public"."preferences" to "service_role";

grant select on table "public"."preferences" to "service_role";

grant trigger on table "public"."preferences" to "service_role";

grant truncate on table "public"."preferences" to "service_role";

grant update on table "public"."preferences" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."preference_users"
as permissive
for all
to authenticated
using (true);


create policy "Enable read access for authenticated users"
on "public"."preferences"
as permissive
for all
to authenticated
using (true);



