-- Phase 1.5 (permission overhaul): app_events
--
-- Normalized, low-PHI event stream for KPI reporting and authorization
-- denial tracking. The existing `audit_log` table remains the HIPAA
-- compliance trail; `app_events` is the analytics surface. Both streams
-- should share `request_id` for correlation.
--
-- KPI dashboards in Phase 7 read views built on top of this table - never
-- raw `audit_log.details` blobs.

CREATE TABLE IF NOT EXISTS public.app_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  event_name text NOT NULL,
  actor_user_id uuid REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  actor_role_ids bigint[] NOT NULL DEFAULT '{}',
  permission_key text REFERENCES public.permission_catalog(key) ON UPDATE CASCADE ON DELETE SET NULL,
  permission_source text NOT NULL DEFAULT 'system'
    CHECK (permission_source IN ('legacy', 'new', 'both', 'system', 'none')),
  outcome text NOT NULL
    CHECK (outcome IN ('success', 'denied', 'failed')),
  feature_area text NOT NULL,
  resource_type text,
  resource_id text,
  subject_patient_id bigint REFERENCES public.patients(id) ON UPDATE CASCADE ON DELETE SET NULL,
  subject_denial_id bigint REFERENCES public.denials(id) ON UPDATE CASCADE ON DELETE SET NULL,
  request_id text,
  session_id text,
  duration_ms integer,
  count integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.app_events ENABLE ROW LEVEL SECURITY;

-- Authenticated users can write their own events.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'app_events'
      AND policyname = 'app_events_insert_self'
  ) THEN
    CREATE POLICY "app_events_insert_self"
      ON public.app_events
      AS PERMISSIVE FOR INSERT TO authenticated
      WITH CHECK (actor_user_id = auth.uid() OR actor_user_id IS NULL);
  END IF;
END $$;

-- Read policy: own rows always, plus admins with audit_read (legacy) or
-- audit.read (resolved via role_permissions once Phase 4 is live).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'app_events'
      AND policyname = 'app_events_read_self_or_audit'
  ) THEN
    CREATE POLICY "app_events_read_self_or_audit"
      ON public.app_events
      AS PERMISSIVE FOR SELECT TO authenticated
      USING (
        actor_user_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM public.users u
          JOIN public.roles r ON u.role = r.id
          WHERE u.id = auth.uid()
            AND COALESCE((r.permissions->>'audit_read')::boolean, false) = true
        )
      );
  END IF;
END $$;

-- No UPDATE / DELETE policies - events are immutable.

GRANT SELECT, INSERT ON public.app_events TO authenticated;
GRANT ALL            ON public.app_events TO service_role;

CREATE INDEX IF NOT EXISTS idx_app_events_actor_created
  ON public.app_events (actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_events_event_created
  ON public.app_events (event_name, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_events_subject_denial
  ON public.app_events (subject_denial_id) WHERE subject_denial_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_app_events_subject_patient
  ON public.app_events (subject_patient_id) WHERE subject_patient_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_app_events_request
  ON public.app_events (request_id) WHERE request_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_app_events_outcome_created
  ON public.app_events (outcome, created_at DESC) WHERE outcome <> 'success';
