-- Phase 5.2: AI Interactions Audit Table
-- Logs all AI exchanges for HIPAA audit trail.

CREATE TABLE IF NOT EXISTS ai_interactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  denial_id bigint REFERENCES denials(id) ON UPDATE CASCADE ON DELETE SET NULL,
  interaction_type text NOT NULL
    CHECK (interaction_type IN ('chat', 'summary_tool', 'appeal_tool', 'query_tool')),
  tool_name text,
  prompt_summary text,
  response_summary text,
  model_used text,
  tokens_used integer,
  duration_ms integer
);

ALTER TABLE ai_interactions ENABLE ROW LEVEL SECURITY;

-- Authenticated users can insert their own AI interaction entries
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'ai_interactions' AND policyname = 'Enable insert for authenticated users'
  ) THEN
    CREATE POLICY "Enable insert for authenticated users"
      ON ai_interactions AS PERMISSIVE FOR INSERT TO authenticated
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- Users can read their own rows; admins can read all
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'ai_interactions' AND policyname = 'Enable read for own rows or admin'
  ) THEN
    CREATE POLICY "Enable read for own rows or admin"
      ON ai_interactions AS PERMISSIVE FOR SELECT TO authenticated
      USING (
        auth.uid() = user_id OR
        EXISTS (
          SELECT 1 FROM users u
          JOIN roles r ON u.role = r.id
          WHERE u.id = auth.uid()
          AND r.permissions->>'admin' = 'true'
        )
      );
  END IF;
END $$;

-- No UPDATE or DELETE policies — AI interaction logs are immutable

CREATE INDEX IF NOT EXISTS idx_ai_interactions_user_id ON ai_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_denial_id ON ai_interactions(denial_id);
CREATE INDEX IF NOT EXISTS idx_ai_interactions_created_at ON ai_interactions(created_at);
