-- Phase 1.3 (permission overhaul): user_role_assignments
--
-- Active and historical role assignments. Replaces the single `users.role`
-- column as the long-term source of truth, while `users.role` is kept in
-- sync as a legacy mirror by the dual-write admin UI (Phase 4).
--
-- IMPORTANT - single-active-role decision:
-- For the entire permission overhaul transition we enforce ONE active role
-- per user via the strict partial unique index
-- `user_role_assignments_one_active_role_per_user`. The schema is shaped to
-- support multi-role later, but the strict index stays in place until after
-- legacy reads are removed (review document Phase 8/9).

CREATE TABLE IF NOT EXISTS public.user_role_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  role_id bigint NOT NULL REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  assigned_by uuid REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  revoked_at timestamptz,
  revoked_by uuid REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  reason text,
  CHECK (revoked_at IS NULL OR revoked_at >= assigned_at)
);

ALTER TABLE public.user_role_assignments ENABLE ROW LEVEL SECURITY;

-- Single active role per user during the transition.
CREATE UNIQUE INDEX IF NOT EXISTS user_role_assignments_one_active_role_per_user
  ON public.user_role_assignments (user_id)
  WHERE revoked_at IS NULL;

-- Lookup index for active assignments by user (covers the index above for
-- read paths that filter by user_id only).
CREATE INDEX IF NOT EXISTS idx_user_role_assignments_user_id
  ON public.user_role_assignments (user_id);

CREATE INDEX IF NOT EXISTS idx_user_role_assignments_role_id
  ON public.user_role_assignments (role_id);

CREATE INDEX IF NOT EXISTS idx_user_role_assignments_active
  ON public.user_role_assignments (user_id, role_id)
  WHERE revoked_at IS NULL;

-- A user may read their own assignment history; admins (audit.read) may
-- read all. Mutations go through service-role / SECURITY DEFINER functions.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'user_role_assignments'
      AND policyname = 'user_role_assignments_read_self_or_audit'
  ) THEN
    CREATE POLICY "user_role_assignments_read_self_or_audit"
      ON public.user_role_assignments
      AS PERMISSIVE FOR SELECT TO authenticated
      USING (
        user_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM public.users u
          JOIN public.roles r ON u.role = r.id
          WHERE u.id = auth.uid()
            AND COALESCE((r.permissions->>'audit_read')::boolean, false) = true
        )
      );
  END IF;
END $$;

GRANT SELECT ON public.user_role_assignments TO authenticated;
GRANT ALL    ON public.user_role_assignments TO service_role;
