-- Phase 1.9.2: Create PHI audit log table with RLS
-- Required by login rate limiting (Phase 2.1) and audit logging throughout the app.

CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  ip_address inet,
  user_agent text,
  details jsonb
);

ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

-- Authenticated users can insert their own audit entries
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'audit_log' AND policyname = 'Enable insert for authenticated users'
  ) THEN
    CREATE POLICY "Enable insert for authenticated users"
      ON audit_log AS PERMISSIVE FOR INSERT TO authenticated
      WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
  END IF;
END $$;

-- Only admin users with audit_read permission can read audit logs
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'audit_log' AND policyname = 'Enable read for admin users'
  ) THEN
    CREATE POLICY "Enable read for admin users"
      ON audit_log AS PERMISSIVE FOR SELECT TO authenticated
      USING (EXISTS (
        SELECT 1 FROM users u
        JOIN roles r ON u.role = r.id
        WHERE u.id = auth.uid()
        AND r.permissions->>'audit_read' = 'true'
      ));
  END IF;
END $$;

-- No UPDATE or DELETE policies — audit logs are immutable

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource ON audit_log(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
