-- Phase 5.5: Conversations Table
-- Stores chat history server-side, scoped to user_id + session_id.
-- Cleared on sign-out (Phase 4.4.1).

CREATE TABLE IF NOT EXISTS conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  session_id text NOT NULL,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'tool')),
  content text NOT NULL,
  tool_name text,
  context_snapshot jsonb
);

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;

-- Users can perform all operations on their own conversations
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'conversations' AND policyname = 'Users manage their own conversations'
  ) THEN
    CREATE POLICY "Users manage their own conversations"
      ON conversations AS PERMISSIVE FOR ALL TO authenticated
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_conversations_user_session ON conversations(user_id, session_id);
